# Generated by Django 6.0.1 on 2026-01-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_manager_created_at_member_created_at_and_more'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
