# Generated by Django 6.0.1 on 2026-01-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_trainer_address_alter_trainer_phone_number'),
        ('workouts', '0002_workouttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberWorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='accounts.member')),
                ('workoutplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_workouts', to='workouts.workoutplan')),
            ],
            options={
                'unique_together': {('workoutplan', 'member')},
            },
        ),
    ]
